### ISSUE TITLE
API runs in Demo Mode?

### ISSUE THREAD

**Issue by glad2badad** [benkeen/generatedata#421] opened 2017-05-17 12:19 UTC
Generating some API calls and noticed that the number of results returned was not exceeding 100 rows.  I had set the $maxGeneratedRows = 1000 in settings.php file.

After some playing around I was able to determine that the $maxDemoModeRows parameter was being evaluated using the API.  Once I overrode that parameter by adding it to the settings.php file and setting the value to 1000, everything works fine.

Why is Demo Mode even a factor with using the API?  Bug?

**Comment by benkeen** [comment] 2017-05-18 12:03
Sure sounds like a bug! Quick clarification: is your installation running in demo mode?

**Comment by glad2badad** [comment] 2017-05-18 12:10
Not sure.  I installed it with the multi-user option.  I can login, save data sets, set custom output / record numbers, etc... 

Is there a flag somewhere that I'm missing?  Maybe some db value I need to update?

**Comment by glad2badad** [comment] 2017-05-25 10:11
LOL.  Was your question a tease?

**Comment by benkeen** [comment] 2017-07-29 21:35
haha no no, I was being serious. :) It works fine for me, but I must admit there's a couple of really fishy bits of code that make me suspicious [these lines of code don't exactly fill me with confidence: https://github.com/benkeen/generatedata/blob/master/resources/classes/Core.class.php#L227-L233 ;) ]. 

Still an issue for you? I'm going to refactor a couple of things around this code now.

**Comment by glad2badad** [comment] 2017-07-31 14:16
Still an issue?  Yes, sort of, but will remain that way as I don't anticipate grabbing a newer version of generatedata code.  I've just left the parameters in the settings.php file and will continue to run it that way.

**Comment by benkeen** [comment] 2017-09-09 17:37
Since I haven't been able to reproduce this & you're on an older version of the code I'm going to close it for now. [Just cleaning up some old tickets]

**Closed by benkeen** 2017-09-09 17:37 UTC
