### ISSUE TITLE
Cycle installation from 5th step to 3th

### ISSUE THREAD

**Issue by blink2004** [benkeen/generatedata#287] opened 2015-05-15 15:53 UTC
After inputed all data and click "Go to script >>" button load 3th step page ("User Accounts") instead of main page of app.
Input all data again, from 3th step to 5th. Again click "Go to script" button and again 3th page loaded.

**Comment by blink2004** [comment] 2015-05-15 15:58
On step #2 create setting file, created file is empty. No inputed data in step 1 no writing to settings.php...

**Comment by benkeen** [comment] 2015-05-19 04:03
Thanks @blink2004! I'm looking at the installation problems for the next version.

**Comment by benkeen** [comment] 2015-05-23 20:41
Hmm - the blank settings file is exceedingly puzzling... can't see how that would occur, very strange.

But it makes sense that you'd be redirected to the step 3 of installation script if the settings file is empty, though: the script automatically detects if (a) the installation is marked as complete and (b) if the settings file has been created. If it's not installed but the settings file exists, it redirects you to the most appropriate step in the installation process (step 3, after the settings file has been created).

What I'll do is add an additional check to confirm the settings file contains valid values.

**Comment by benkeen** [comment] 2015-05-26 01:33
Duplicate of #249

**Closed by benkeen** 2015-05-26 01:33 UTC
